name: "emscripten build"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.19
          actions-cache-folder: 'emsdk-cache'

      - name: Verify
        run: emcc -v

      - name: Get latest CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Configure CMake
        run: |
          mkdir build
          cd build
          emcmake cmake ..

      - name: Build project
        run: |
          cd build
          emmake make

      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4 
        with:
          name: RobotPalWeb
          path: |
            ./build/RobotPal/*.html
            ./build/RobotPal/*.js
            ./build/RobotPal/*.wasm
            ./build/RobotPal/*.data
          retention-days: 1
